"use client"
import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'fr' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  fr: {
    // Header & User
    'user.profile': 'Mon profil',
    'user.settings': 'Paramètres',
    'user.logout': 'Se déconnecter',
    'user.manageInfo': 'Gérer vos informations',
    'user.preferences': 'Préférences et configuration',
    'user.role': 'Consultant',
    'agency.select': 'Sélectionner une agence',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.unread': 'non lue',
    'notifications.unreadPlural': 'non lues',
    'notifications.markAllRead': 'Tout marquer comme lu',
    'notifications.viewAll': 'Voir toutes les notifications',
    'notifications.none': 'Aucune notification',
    'notifications.invoice.validated': 'Nouvelle facture validée',
    'notifications.invoice.validatedMsg': 'La facture FACT-2025-045 a été validée',
    'notifications.payment.late': 'Paiement en retard',
    'notifications.payment.lateMsg': 'Le paiement de Maxam Ghana est en retard de 3 jours',
    'notifications.folder.completed': 'Dossier complété',
    'notifications.folder.completedMsg': 'Le dossier DOS-2025-123 a été complété avec succès',
    'notifications.client.new': 'Nouveau client',
    'notifications.client.newMsg': 'Un nouveau client a été ajouté au système',
    'notifications.time.min': 'Il y a 5 min',
    'notifications.time.1h': 'Il y a 1h',
    'notifications.time.2h': 'Il y a 2h',
    'notifications.time.3h': 'Il y a 3h',
    
    // Sidebar Modules
    'module.dashboard': 'Tableau de bord',
    'module.operations': 'Opérations',
    'module.operations.folders': 'Dossiers',
    'module.logistics': 'Logistique & Transit',
    'module.logistics.maritime': 'Déconsolidation Maritime',
    'module.logistics.air': 'Déconsolidation Aérienne',
    'module.logistics.doc': 'Doc Release',
    'module.logistics.customs': 'Déclaration Douanière',
    'module.shipping': 'Shipping',
    'module.consignment': 'Consignation',
    'module.trucking': 'Trucking',
    'module.other': 'Autres Activités',
    'module.crm': 'CRM',
    'module.crm.activities': 'Activités',
    'module.crm.customers': 'Clients',
    'module.crm.contacts': 'Contacts',
    'module.sales': 'Ventes',
    'module.sales.quotes': 'Devis & Proforma',
    'module.sales.debtors': 'Débiteurs / Clients',
    'module.sales.invoicing': 'Facturation',
    'module.purchases': 'Achats',
    'module.purchases.requests': 'Demandes d\'achat',
    'module.purchases.creditors': 'Créanciers / Fournisseurs',
    'module.purchases.orders': 'Bons de commande',
    'module.accounting': 'Comptabilité',
    'module.accounting.plan': 'Plan comptable',
    'module.accounting.general': 'Comptabilité générale',
    'module.accounting.treasury': 'Trésorerie',
    'module.stock': 'Stock',
    'module.stock.inventory': 'Inventaire',
    'module.stock.movements': 'Mouvements',
    'module.hr': 'Ressources Humaines',
    'module.hr.employees': 'Employés',
    'module.hr.payroll': 'Paie',
    'module.hr.leaves': 'Congés',
    'module.reports': 'Rapports',
    'module.reports.financial': 'Financiers',
    'module.reports.operational': 'Opérationnels',
    'module.config': 'Configuration',
    'module.config.system': 'Système',
    'module.config.users': 'Utilisateurs',
    'module.config.params': 'Paramètres',
    
    // Purchase Requests
    'purchases.title': 'Demandes d\'achat',
    'purchases.subtitle': 'Gestion et suivi des demandes d\'achat',
    'purchases.newRequest': 'Nouvelle demande',
    'purchases.export': 'Exporter',
    'purchases.settings': 'Paramètres',
    'purchases.actions.new': 'Nouvelle demande',
    'purchases.actions.export': 'Exporter',
    'purchases.stats.total': 'Total demandes',
    'purchases.stats.toApprove': 'À approuver',
    'purchases.stats.justifications': 'Justificatifs',
    'purchases.stats.paid': 'Payés',
    'purchases.stats.unpaid': 'Non payés',
    'purchases.stats.urgent': 'urgent(s)',
    'purchases.stats.late': 'en retard',
    'purchases.stats.ofTotal': 'du total',
    'purchases.filters.title': 'Filtres rapides',
    'purchases.filters.all': 'Toutes les demandes',
    'purchases.filters.pendingApproval': 'En attente d\'approbation',
    'purchases.filters.pendingJustification': 'En attente de justificatif',
    'purchases.filters.paid': 'Achats payés',
    'purchases.filters.unpaid': 'Achats non payés',
    'purchases.filters.late': 'en retard',
    'purchases.alerts.title': 'Rappels automatiques',
    'purchases.alerts.message': 'demande(s) en attente de justificatif depuis plus de 3 jours',
    'purchases.alerts.sendReminders': 'Envoyer rappels',
    'purchases.filter.all': 'Toutes les demandes',
    'purchases.filter.pending': 'En attente d\'approbation',
    'purchases.filter.justification': 'En attente de justificatif',
    'purchases.filter.paid': 'Achats payés',
    'purchases.filter.unpaid': 'Achats non payés',
    'purchases.filter.quickFilters': 'Filtres rapides',
    'purchases.filter.actionRequired': 'Action requise',
    'purchases.reminder.title': 'Rappels automatiques',
    'purchases.reminder.message': 'demande(s) en attente de justificatif depuis plus de 3 jours',
    'purchases.reminder.send': 'Envoyer rappels',
    'purchases.quickStats.totalAmount': 'Montant total',
    'purchases.quickStats.urgent': 'Demandes urgentes',
    'purchases.search.placeholder': 'Rechercher par référence, fournisseur, service...',
    'purchases.search.advanced': 'Recherche avancée',
    'purchases.search.supplier': 'Fournisseur',
    'purchases.search.supplierPlaceholder': 'Nom du fournisseur',
    'purchases.search.department': 'Service demandeur',
    'purchases.search.departmentPlaceholder': 'Service',
    'purchases.search.dateFrom': 'Date de début',
    'purchases.search.dateTo': 'Date de fin',
    'purchases.search.minAmount': 'Montant min',
    'purchases.search.maxAmount': 'Montant max',
    'purchases.search.reset': 'Réinitialiser',
    'purchases.table.reference': 'Référence',
    'purchases.table.title': 'Titre',
    'purchases.table.supplier': 'Fournisseur',
    'purchases.table.department': 'Service',
    'purchases.table.requester': 'Demandeur',
    'purchases.table.amount': 'Montant',
    'purchases.table.priority': 'Priorité',
    'purchases.table.approval': 'Approbation',
    'purchases.table.justification': 'Justification',
    'purchases.table.payment': 'Paiement',
    'purchases.table.linkedDocs': 'Docs liés',
    'purchases.table.actions': 'Actions',
    'purchases.status.pending': 'En attente',
    'purchases.status.approved': 'Approuvé',
    'purchases.status.rejected': 'Rejeté',
    'purchases.status.justificationPending': 'Justificatif attendu',
    'purchases.status.justified': 'Justifié',
    'purchases.status.notRequired': 'Non requis',
    'purchases.status.paid': 'Payé',
    'purchases.status.unpaid': 'Non payé',
    'purchases.status.partiallyPaid': 'Partiellement payé',
    'purchases.priority.urgent': 'Urgent',
    'purchases.priority.normal': 'Normal',
    'purchases.priority.low': 'Bas',
    'purchases.tooltip.invoice': 'Facture',
    'purchases.tooltip.purchaseOrder': 'Bon de commande',
    'purchases.tooltip.view': 'Voir les détails',
    'purchases.tooltip.edit': 'Modifier',
    'purchases.tooltip.more': 'Plus d\'options',
    'purchases.tooltip.justificationLate': 'Justificatif en retard de',
    'purchases.tooltip.days': 'jours',
    'purchases.empty.title': 'Aucune demande d\'achat trouvée',
    'purchases.empty.subtitle': 'Essayez de modifier vos filtres de recherche',
    
    // Common
    'common.search': 'Rechercher',
    'common.filter': 'Filtrer',
    'common.export': 'Exporter',
    'common.import': 'Importer',
    'common.new': 'Nouveau',
    'common.edit': 'Modifier',
    'common.delete': 'Supprimer',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.close': 'Fermer',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.loading': 'Chargement...',
    'common.inDevelopment': 'En développement',
  },
  en: {
    // Header & User
    'user.profile': 'My Profile',
    'user.settings': 'Settings',
    'user.logout': 'Log Out',
    'user.manageInfo': 'Manage your information',
    'user.preferences': 'Preferences and configuration',
    'user.role': 'Consultant',
    'agency.select': 'Select an agency',
    
    // Notifications
    'notifications.title': 'Notifications',
    'notifications.unread': 'unread',
    'notifications.unreadPlural': 'unread',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.viewAll': 'View all notifications',
    'notifications.none': 'No notifications',
    'notifications.invoice.validated': 'New invoice validated',
    'notifications.invoice.validatedMsg': 'Invoice FACT-2025-045 has been validated',
    'notifications.payment.late': 'Late payment',
    'notifications.payment.lateMsg': 'Payment from Maxam Ghana is 3 days overdue',
    'notifications.folder.completed': 'Folder completed',
    'notifications.folder.completedMsg': 'Folder DOS-2025-123 has been successfully completed',
    'notifications.client.new': 'New client',
    'notifications.client.newMsg': 'A new client has been added to the system',
    'notifications.time.min': '5 min ago',
    'notifications.time.1h': '1h ago',
    'notifications.time.2h': '2h ago',
    'notifications.time.3h': '3h ago',
    
    // Sidebar Modules
    'module.dashboard': 'Dashboard',
    'module.operations': 'Operations',
    'module.operations.folders': 'Folders',
    'module.logistics': 'Logistics & Transit',
    'module.logistics.maritime': 'Maritime Deconsolidation',
    'module.logistics.air': 'Air Deconsolidation',
    'module.logistics.doc': 'Doc Release',
    'module.logistics.customs': 'Customs Declaration',
    'module.shipping': 'Shipping',
    'module.consignment': 'Consignment',
    'module.trucking': 'Trucking',
    'module.other': 'Other Activities',
    'module.crm': 'CRM',
    'module.crm.activities': 'Activities',
    'module.crm.customers': 'Customers',
    'module.crm.contacts': 'Contacts',
    'module.sales': 'Sales',
    'module.sales.quotes': 'Quotes & Proforma',
    'module.sales.debtors': 'Debtors / Customers',
    'module.sales.invoicing': 'Invoicing',
    'module.purchases': 'Purchases',
    'module.purchases.requests': 'Purchase Requests',
    'module.purchases.creditors': 'Creditors / Suppliers',
    'module.purchases.orders': 'Purchase Orders',
    'module.accounting': 'Accounting',
    'module.accounting.plan': 'Chart of Accounts',
    'module.accounting.general': 'General Accounting',
    'module.accounting.treasury': 'Treasury',
    'module.stock': 'Stock',
    'module.stock.inventory': 'Inventory',
    'module.stock.movements': 'Movements',
    'module.hr': 'Human Resources',
    'module.hr.employees': 'Employees',
    'module.hr.payroll': 'Payroll',
    'module.hr.leaves': 'Leaves',
    'module.reports': 'Reports',
    'module.reports.financial': 'Financial',
    'module.reports.operational': 'Operational',
    'module.config': 'Configuration',
    'module.config.system': 'System',
    'module.config.users': 'Users',
    'module.config.params': 'Parameters',
    
    // Purchase Requests
    'purchases.title': 'Purchase Requests',
    'purchases.subtitle': 'Purchase request management and tracking',
    'purchases.newRequest': 'New request',
    'purchases.export': 'Export',
    'purchases.settings': 'Settings',
    'purchases.actions.new': 'New request',
    'purchases.actions.export': 'Export',
    'purchases.stats.total': 'Total requests',
    'purchases.stats.toApprove': 'To approve',
    'purchases.stats.justifications': 'Justifications',
    'purchases.stats.paid': 'Paid',
    'purchases.stats.unpaid': 'Unpaid',
    'purchases.stats.urgent': 'urgent',
    'purchases.stats.late': 'late',
    'purchases.stats.ofTotal': 'of total',
    'purchases.filters.title': 'Quick filters',
    'purchases.filters.all': 'All requests',
    'purchases.filters.pendingApproval': 'Pending approval',
    'purchases.filters.pendingJustification': 'Pending justification',
    'purchases.filters.paid': 'Paid purchases',
    'purchases.filters.unpaid': 'Unpaid purchases',
    'purchases.filters.late': 'late',
    'purchases.alerts.title': 'Automatic reminders',
    'purchases.alerts.message': 'request(s) pending justification for more than 3 days',
    'purchases.alerts.sendReminders': 'Send reminders',
    'purchases.filter.all': 'All requests',
    'purchases.filter.pending': 'Pending approval',
    'purchases.filter.justification': 'Pending justification',
    'purchases.filter.paid': 'Paid purchases',
    'purchases.filter.unpaid': 'Unpaid purchases',
    'purchases.filter.quickFilters': 'Quick filters',
    'purchases.filter.actionRequired': 'Action required',
    'purchases.reminder.title': 'Automatic reminders',
    'purchases.reminder.message': 'request(s) pending justification for more than 3 days',
    'purchases.reminder.send': 'Send reminders',
    'purchases.quickStats.totalAmount': 'Total amount',
    'purchases.quickStats.urgent': 'Urgent requests',
    'purchases.search.placeholder': 'Search by reference, supplier, department...',
    'purchases.search.advanced': 'Advanced search',
    'purchases.search.supplier': 'Supplier',
    'purchases.search.supplierPlaceholder': 'Supplier name',
    'purchases.search.department': 'Requesting department',
    'purchases.search.departmentPlaceholder': 'Department',
    'purchases.search.dateFrom': 'From date',
    'purchases.search.dateTo': 'To date',
    'purchases.search.minAmount': 'Min amount',
    'purchases.search.maxAmount': 'Max amount',
    'purchases.search.reset': 'Reset',
    'purchases.table.reference': 'Reference',
    'purchases.table.title': 'Title',
    'purchases.table.supplier': 'Supplier',
    'purchases.table.department': 'Department',
    'purchases.table.requester': 'Requester',
    'purchases.table.amount': 'Amount',
    'purchases.table.priority': 'Priority',
    'purchases.table.approval': 'Approval',
    'purchases.table.justification': 'Justification',
    'purchases.table.payment': 'Payment',
    'purchases.table.linkedDocs': 'Linked docs',
    'purchases.table.actions': 'Actions',
    'purchases.status.pending': 'Pending',
    'purchases.status.approved': 'Approved',
    'purchases.status.rejected': 'Rejected',
    'purchases.status.justificationPending': 'Justification pending',
    'purchases.status.justified': 'Justified',
    'purchases.status.notRequired': 'Not required',
    'purchases.status.paid': 'Paid',
    'purchases.status.unpaid': 'Unpaid',
    'purchases.status.partiallyPaid': 'Partially paid',
    'purchases.priority.urgent': 'Urgent',
    'purchases.priority.normal': 'Normal',
    'purchases.priority.low': 'Low',
    'purchases.tooltip.invoice': 'Invoice',
    'purchases.tooltip.purchaseOrder': 'Purchase order',
    'purchases.tooltip.view': 'View details',
    'purchases.tooltip.edit': 'Edit',
    'purchases.tooltip.more': 'More options',
    'purchases.tooltip.justificationLate': 'Justification overdue by',
    'purchases.tooltip.days': 'days',
    'purchases.empty.title': 'No purchase requests found',
    'purchases.empty.subtitle': 'Try modifying your search filters',
    
    // Common
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.new': 'New',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.close': 'Close',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.loading': 'Loading...',
    'common.inDevelopment': 'Under development',
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('fr');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}